[package]
name = "llmtool"
version = "0.1.0"
edition = "2024"
authors = ["Jan Bujak <jan@exia.io>"]
license = "MIT/Apache-2.0"
repository = "https://github.com/koute/llmtool"

[[bin]]
name = "lt"
path = "src/main.rs"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1", features = ["preserve_order", "float_roundtrip"] }
tokio = { version = "1", features = ["full"] }
reqwest = { version = "0.13", features = ["json", "stream"] }
futures = "0.3"
ctrlc = "3"
clap = { version = "4.5.34", features = ["derive"] }
memmap2 = "0.9.5"
memchr = "2.7.5"
rayon = "1.11.0"
tikv-jemallocator = "0.6.1"
blake3 = "1.8.2"
ahash = "0.8.12"
time = { version = "0.3", features = ["formatting", "local-offset"] }
hyper = { version = "1", features = ["http1", "http2", "client", "server"], default-features = false }
hyper-util = "0.1"
http = "1"
bytes = "1"
http-body = "1"
http-body-util = "0.1"
tokio-stream = "0.1"
parking_lot = { version = "0.12.5", features = ["send_guard"] }
dialoguer = "0.12.0"
libc = "0.2"
landlock = "0.4.4"
minijinja = "2.15.1"
syntect = "5.3.0"
diff = "0.1.13"
async-trait = "0.1.89"
rand = "0.9.2"
base64 = "0.22"
image = { version = "0.25", default-features = false, features = ["jpeg", "png", "webp", "avif", "nasm", "rayon"] }
fast_image_resize = { version = "6", features = ["image", "rayon"] }
